language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.2.5.0 # JRuby in 2.5 mode
services:
  - mongodb
gemfile:
  - gemfiles/mongoid5.gemfile
  - gemfiles/mongoid6.gemfile
  - gemfiles/mongoid7.gemfile
