language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-9.2.11.1 # JRuby in 2.5 mode
services:
  - mongodb
gemfile:
  - gemfiles/mongoid5.gemfile
  - gemfiles/mongoid6.gemfile
  - gemfiles/mongoid7.gemfile
jobs:
  exclude:
    - rvm: 2.7.1
      gemfile: gemfiles/mongoid5.gemfile # mongoid 5.x uses BigDecimal.new, removed in Ruby 2.7
